### ISSUE TITLE
File system paths with spaces and symbols

### ISSUE THREAD

**Issue by tsabolov** [UniversaBlockchain/universa#10]
It seems that uniclient's `--check` parameter does not understand paths with spaces. Didn't check other parameters.

P.S. I'm on MacOS btw.

**Comment by identifyuserr** [comment]
What does it mean? I participate in the subscribers bounty . What do I need to check?

**Comment by vladimirpraktika** [comment]
by this link you can check the number of accrued tokens. on the site icobaker.com you can see how many tokens are credited by categories: referrals, bounty, purchase.

> 8 нояб. 2017 г., в 9:57, identifyuserr <notifications@github.com> написал(а):
> 
> What does it mean? I participate in the subscribers bounty . What do I need to check?

**Comment by amyodov** [comment]
@identifyuserr , @vladimirpraktika , please refrain from useless comments that are not related to the ticket being discussed.

**Comment by sergeych** [comment]
Fixed. Use either "file name.unicon" or file\ name.unicon notation. The error was in the bash script. Updated uniclient could be downloaded using the link in docs.
