### ISSUE TITLE
0 UTN

### ISSUE THREAD

**Issue by Licket** [UniversaBlockchain/universa#12]
Dear team, I have sent eth from my kickico address, and asked them why I haven't received any UTN tokens. They tell me, that I should contact you. 

So. Why are my balance 0 ? 

My best regards from here

**Comment by amyodov** [comment]
Please refrain from using GitHub tickets for Universa network codebase for purposes not related to the Universa development.

**Comment by Licket** [comment]
Of course, I am sorry - I had no idea it was wrong to do.

I don't have a smartphone though, so I can't join telegram, and your email
is not public, so I was wondering if you could tell me, where/who to
contact for issues with the universa token?

My best regards

**Comment by amyodov** [comment]
You can use a desktop or web version of Telegram to contact the support team. Also when paying via Kickico, to get the tokens accounted, you should know that the tokens get delivered to the check.universa.io account _which has the same email as your kickico profile_; so if you don’t have such an account yet, just create it with the same email, and they appear on it in some time.

**Comment by Licket** [comment]
Thank you. They just appeared (weren't there before)

Fyi, everybody seems to think that it is - but it is not possible to log
into telegram without creating an account on a smartphone beforehand (or
else I am retarded, in that case sorry)

Anyway thank you for your time, which is much appreciated

My best regards
