### ISSUE TITLE
There is a very serious security vulnerability on TestNet

### ISSUE THREAD

**Issue by serdarozturk** [UniversaBlockchain/universa#13]
There is a Cross-Site Scripting security issue on chat messages. You should fix it before MainNet. 

Example: `<a href="javascript:alert(document.cookie);">xss clickable message</a>`

**Comment by serdarozturk** [comment]
And TestNet still does not work on safari browser. 

Safari v9.1 - OSX El Capitan

**Comment by amyodov** [comment]
Thanks for spotting it. Great to get it noticed before the mainnet, indeed. The latest web client (v1.3.3) should have it already resolved.

And by the way, the client seems working in Safari for me; any issues in loading in your case may be environment-specific, so may need to some more details from your side (like, console logs).

Closing this issue for now (as the messages are now well-escaped); if you still have the issue about Safari, feel free to open a separate issue for that and provide more details.
