### ISSUE TITLE
выглядит странно - локальная нода создает всю сеть

### ISSUE THREAD

**Issue by magum** [UniversaBlockchain/universa#2]
https://github.com/UniversaBlockchain/universa/blob/d5d9f74f1487cc3fffa05bb6b20fad71efe19885/universa_core/src/main/java/com/icodici/universa/node/network/NetworkBuilder.java#L123

выглядит странно для понимания
"какая-то одна конкретная нода создает всю сеть"

в сумме все выглядит так: находим в ростере ноду, которая локальная и уже из контекста локальной ноды, перебирая весь ростер опять создаем ВСЮ "сеть".
в смысле выглядело бы логичнее, если бы класс Network создавал NetworkBulder (перебирая ростер), а не NodeInfo

**Comment by sergeych** [comment]
Это не нода. Это другой класс - NodeInfo, информация о ноде. 

Сеть действительно создается _для какой то конкретной ноды_ которая будет локальной. Для всех остальных узлов формируются удаленные интерфейсы. 

Network - абстрацкция сети, она никак не зависит от транспорта между нодами (имплементации Node). NetworkBuilder - построитель сети из локального конфига на конкретных транспортах. Мы изолируем полностью логику выборов от сетевого уровня.
