### ISSUE TITLE
глобально блокирующий http сервер вызов "/network"

### ISSUE THREAD

**Issue by magum** [UniversaBlockchain/universa#3]
https://github.com/UniversaBlockchain/universa/blob/d5d9f74f1487cc3fffa05bb6b20fad71efe19885/universa_core/src/main/java/com/icodici/universa/node/network/ClientEndpoint.java#L202

тут изза synchronized получается что "/network" это глобально блокирующий весь http сервер  вызов. и непонятно ради чего.
Binder networkDirectory это закэшированный ответ. кэшируется он один раз при первом запросе "/network" и больше не предполагается меняться. Я так понял это потому что ростер в рантайме не изменяется. Тк по факту ростер только читается при старте из конфига.
те получается ростер и networkDirectory после создания только реадонли.
тогда зачем блокировать весь хттп сервер? Можно все на старте сделать - создали ростер, 
закэшировали сразу ответ в networkDirectory и возвращаем его на каждый запрос "/network" без блокировок.

если же ростер в будующем будет изменяемый в рантайме, то скоуп synchronized можно уменьшить до конкетного переключения кэша на новое содержимое:
synchronized (this) {
  networkDirectory = network;
}
а предварительно подготавливать содержимое network можно без блокировок, ведь ростер concurenthashmap

но возможно вызов "/network" редкий и не стоит заморачиваться

**Comment by sergeych** [comment]
Спасибо, так и есть. Он вообще макетный тут, реальный работает существенно сложнее - он читает ростер из сети, из нескольких нод, и строит "консенсус", так как клиент не знает реального положения дел. Это заглушка

**Comment by sergeych** [comment]
говорят что нет ничего более постоянного чем временное. спасибо, соптимизировал
