### ISSUE TITLE
я правильно понял что пока не реализованно что в рантайме новые ноды регистрировались?

### ISSUE THREAD

**Issue by magum** [UniversaBlockchain/universa#4]
тк сейчас в рантайме новые ноды создавать нельзя - только из локального конфига и при рестарте

**Comment by sergeych** [comment]
Да. Процедура продажи лицензий на ноды еще не готова - там много юридических и процедурных вопросов, от которых зависит способ принятия новой ноды. Когда процедура будет принята, будут добавлены соответствующие протоколы
