### ISSUE TITLE
вызовы waitSuccess - блокирующие поток

### ISSUE THREAD

**Issue by magum** [UniversaBlockchain/universa#5]
https://github.com/UniversaBlockchain/universa/blob/d5d9f74f1487cc3fffa05bb6b20fad71efe19885/universa_core/src/main/java/com/icodici/universa/node/network/BitrustedRemoteAdapter.java#L57

DeferredResult::waitSuccess вызывает DeferredResult::join а тот Object::wait(0)
те две основные метода класса Node (checkItem и getItem) которые осуществляют запросы к удаленным нодам реализованны НЕ  как асинхронные и блокируют весь поток ожидая ответа из сети ?
получается пару десятков паралельных входящих вызовов и нода "встанет" на ожидании ответа из сети?

кстати по коду каждый вызов Farcall на принимающей стороне создает новый тред. Те настоящий системный тред, те не легковесный (зеленый). Это очень тяжелый вызов получается.

**Comment by sergeych** [comment]
мы используем пулы, которые переиспользуют треды. Выбор треда из пула - легкий вызов. Нативные треды используют все ядра и процессоры системы. 

Обмен между нодами (не клиентами и нодами) сейчас синхронный, при этом сами вызываемые методы не блокирующие, соответственно имеет место только ожидание сети. Потоки для этой цели выбираются из отдельного пула - таким образом, задержки ожидания ответа других нод не могут "остановить" вызывающую ноду - просто выборы встанут в очередь и будут выполняться в том темпе, в котором позволяет сеть, но они в другом темпе выполнятся и не могут. При этом, если консенсус достигнут, ожидающие потоки могут быть прерваны, если раньше не отвалятся по таймауту.

Предполагается, что все ноды устанавливаются на хороших каналах, и TCP транспорт будет работать устойчиво и быстро. Если окажется, что UDP транспорт работает лучше в условиях реальной эксплуатации, мы выпустим вторую версию протокола обмена между нодами, полностью асинхронную, на датаграммах.

**Comment by magum** [comment]
> мы используем пулы, которые переиспользуют треды. Выбор треда из пула - легкий вызов. >Нативные треды используют все ядра и процессоры системы.
про пулы я видел -да. но про создание треда я другое имел ввиду - создание треда worker внутри Farcall. Но потом понял - Farcall создается один раз и живет долго, как и его воркер-тред. Так что я не ошибся не правильно поняв изначально как Farcall работает
