### ISSUE TITLE
уточнение по проводу реальной проверки айтема

### ISSUE THREAD

**Issue by magum** [UniversaBlockchain/universa#6]
https://github.com/UniversaBlockchain/universa/blob/d5d9f74f1487cc3fffa05bb6b20fad71efe19885/universa_core/src/main/java/com/icodici/universa/node/Elections.java#L125

просто хочу уточнить, что я правильно понял код. вся реальная проверка айтема на ЛОКАЛЬНом сервере производится внутри этой ф-ции. все остальное - поиск консенсуса между нодами сети через выборы и/или открытие/закрытие связанных айтемов по факту апрува на основании консенсуса?

**Comment by sergeych** [comment]
Короткий ответ: да. 

Длинный: она выполняется локальным клиентом, а также и всеми нодами во время выборов. Локальный клиент в настоящее время не проверяет внешние связи, так как проще спросить ноду.
