### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by sarg** [UniversaBlockchain/universa#8]
https://github.com/UniversaBlockchain/universa/blob/4c04939bf1e8afb0ae5e605bcc10ac39d59e017c/universa_core/src/main/java/com/icodici/universa/node/ItemResult.java#L108-L119

если expiresAt = null а result2.expriresAt != null, то первые скобки будут false, произойдет вычисление вторых и будет NPE при вызове truncatedTo

**Comment by sergeych** [comment]
спасибо :) исправим. вообще говоря, система не должна вообще разрешать обработку элеменов с expiresAt == null, но проверить лишний раз не помешает. Вопрос только что при этом правильнее сделать - бросать IllegalStateException видимо.

**Comment by sarg** [comment]
поле expiresAt final, правильнее будет проверять корректность объекта в конструкторе.

**Comment by sergeych** [comment]
Или даже задать ему дефолтное значение, соответсвтующее предельному времени
пребывания необработанного документа в леджере.

**Comment by sergeych** [comment]
исправлено в b2ce1bab34eb4424071c9fdfc451283edcb358ee
